blank_issues_enabled: true
contact_links:
  - name: Contentful Support & Help Center
    url: https://support.contentful.com/hc/en-us/
    about: Submit a support ticket or browse the help center.
  - name: Contentful Developer Portal
    url: https://www.contentful.com/developers/
    about: Browse the developer portal for documentation, tutorials, and more.
  - name: Contentful Community Discord
    url: https://www.contentful.com/discord/
    about: Get peer support on the Contentful Community Discord.
